name: luxury
description: Learn the basics of using Material Components by building a simple app with core components.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
   # TODO: Add slanted menu asset (104)
  uses-material-design: true
  assets:
    - assets/logoperhiasan.png
    - assets/perhiasan1.jpg
    - assets/perhiasan2.jpg
    - assets/perhiasan3.jpg
    - assets/perhiasan4.jpg
    - assets/perhiasan5.jpg
    - assets/perhiasan6.jpg
    - assets/perhiasan7.jpg
    - assets/perhiasan8.jpg
    - assets/perhiasan9.jpg
    - assets/perhiasan10.jpg
    - assets/perhiasan11.jpg
    - assets/perhiasan12.jpg
    - assets/perhiasan13.jpg
    - assets/perhiasan14.jpg
    - assets/perhiasan15.jpg
    - assets/perhiasan16.jpg
    - assets/perhiasan17.jpg
    - assets/perhiasan18.jpg
    - assets/perhiasan19.jpg
    - assets/perhiasan20.jpg
    - assets/perhiasan21.jpg
    - assets/perhiasan22.jpg
    - assets/perhiasan23.jpg
    - assets/perhiasan24.jpg
    - assets/perhiasan25.jpg
    - assets/perhiasan26.jpg
    - assets/perhiasan27.jpg
    - assets/perhiasan28.jpg
    - assets/perhiasan29.jpg
    - assets/perhiasan30.jpg
    - assets/perhiasan31.jpg
    - assets/perhiasan32.jpg
    - assets/perhiasan33.jpg
    - assets/perhiasan34.jpg
    - assets/perhiasan35.jpg
    - assets/perhiasan36.jpg
    - assets/perhiasan37.jpg
    - assets/perhiasan38.jpg
    
   